### ISSUE TITLE
AssertionError when authenticated

### ISSUE THREAD

**Issue by osso73** [osso73/garmin-backup#9]
This is the error:

```
Connecting to Garmin Connect...
Trying to login to Garmin Connect using token data from directory '~/.garminconnect'...

Traceback (most recent call last):
  File "C:\Cloud\Data\Programacion\GitHub\garmin-backup\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Cloud\Data\Programacion\GitHub\garmin-backup\.venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "garmin-backup.py", line 361, in <module>
  File "garmin-backup.py", line 329, in main
  File "garmin-backup.py", line 98, in init_api
  File "c:\Cloud\Data\Programacion\GitHub\garmin-backup\.venv\Lib\site-packages\garminconnect\__init__.py", line 186, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "c:\Cloud\Data\Programacion\GitHub\garmin-backup\.venv\Lib\site-packages\garth\http.py", line 104, in profile
    assert isinstance(self._profile, dict)
AssertionError
```

This is the same error as reported [here](https://github.com/cyberjunky/python-garminconnect/issues/238) in the `python-garminconnect` library. It is linked to a change in the authentication API of Gramin introducing MFA, as documented [here](https://github.com/cyberjunky/python-garminconnect/issues/235).

It has now been fixed, I need to update my requirements file and fix it. Will create a new exe version.

**Comment by osso73** [comment]
Updated garminconnect library, and the error is fixed, as per commit e4d4157.
